spring:
  datasource:
    username: root
    password: dir999
    url: jdbc:mysql://localhost:3306/music?useSSL=false&serverTimezone=GMT%2d8
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      #单文件最大上传为50mb，多文件上传最多100mb
      max-file-size: 50MB
      max-request-size: 100MB

# 自定义配置
config:
  origin: "*"
  interface: "https://fafafafa.site:4400"

server:
  port: 4400
  ssl:
    enabled: true
    key-store: classpath:https.jks
    key-store-password: 123456
    key-store-type: jks

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    #        path: C:/Users/Young/Desktop/Works/daerxia/软件工程/Project/files/
    path: /home/music/files/
