spring:
  datasource:
    username: root
    password: dir99
    url: jdbc:mysql://localhost:3306/music?useSSL=false&serverTimezone=GMT%2d8
#    url: jdbc:mysql://47.94.161.201:3306/music?useSSL=false&serverTimezone=GMT%2d8
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      #单文件最大上传为50mb，多文件上传最多100mb
      max-file-size: 50MB
      max-request-size: 100MB

# 自定义配置
config:
  origin: "http://localhost"
#  origin: "http://47.94.161.201"
  interface: "http://localhost:8080"
#  interface: "http://47.94.161.201:8080"

server:
  port: 8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
        path: C:/Users/Young/Desktop/Works/daerxia/软件工程/Project/files/
#    path: /home/files/
